<div class="input-field">
    <input id="name" type="text" name="name" value="${product.name}"/>
    <label for="name">Name</label>
</div>
<div class="input-field">
    <input id="description" type="text" name="description" value="${product.description}"/>
    <label for="description">Description</label>
</div>
<div class="input-field">
    <input id="price" type="number" step="0.01" name="price" value="${product.price}"/>
    <label for="price">Price</label>
</div>